### DISCUSSION TITLE
Wallbox charger jumps to 32A after current adjustment

### DISCUSSION THREAD

**Discussion by taste66** [lbbrhzn/ocpp#1482] [Q&A]
I have this strange bug for which I do not know if this is my Wallbox OCPP behavior of part of this integration.
I adjust the charge current regularly based of the total power entering my home. The charger can do 32A maximum, my main fuse is 35A so this is important. Initially I was updating the current every minute and ran into the problem it sometimes jumped to 32A current offered while maximum current was still set to a much lower value. Resending the same value did not fix the problem it needed to be something different.

I changed to only send a new value if it was at least 2A different than the old one which reduced the problem a lot but it is still there. I now added the Wallbox integration and are also sending the max charge current trough that control, 15s after I did send it through OCPP. It still happens but the high current is now limited to 20s so the Wallbox integration gets it right, as you can see on the graph below:
![image](https://github.com/user-attachments/assets/efa49734-1fe5-4bb8-83cb-c58c919824ba)

I do not like doing through a cloud connected service since it is an additional failuremode for it to not work. Is there a way to see in logging what OCPP is actually sending to the Walbox? If this is right I guess I need to file a bug at Wallbox but I would be surprised I am the only one suffering from it. I am running firmware 6.4.14 on a Wallbox Pulsar Plus

**Comment by lbbrhzn** [comment]
I believe the wallbox pulsar plus only supports specific values for the maximum current.

**Comment by taste66** [comment]
@lbbrhzn Thank you for responding. I am afraid the specific current is not the problem since it does work most of the time. When it goes wrong I send the same value trough the wallbox integration and that does work. Leave this work around in there for now and check  after a Wallbox SW update.

**Reply by rbb-dev** [reply]
Without seeing the logs, no one can help you.
But from my experience, I have a charger that jumps to 32A if I set anything from 0 to 5A
It also faults and stops charging few seconds after I send it 7A.
It also goes to 32A if I send it any floating point value, 27.5 for example.
You just have to inspect the logs to see what is happening..

**Comment by taste66** [comment]
@rbb-dev Thank you, I double checked but I am only sending integer numbers. I can reproduce relative easy by using actions in the development menu. I did test with send the maximum current to 10 amps which shows up in the logs as 10.0
when I get the green check in the action GUI I press the button again after 3 times the current jumps to 32A
[occp.log](https://github.com/user-attachments/files/18401898/occp.log)
In this logfile I set to 10A in line 30, 42, 48 and 54 I think the 23 inbetween is my normal automation getting in between

At line 56 you see the current offered is 32 A which is again updated to 23 A after 20s by my automation.
I know I am doing far to quickly but this also happens if I modify the current once per minute.

**Reply by rbb-dev** [reply]
in the space of 10 seconds, you send 4 csChargingProfiles to the charger.
After that, it reports that Current.Offered = 32A
i think you're confusing it.. its way to frequent
try reducing the frequency to 60 sends and see if it continues.

**Comment by taste66** [comment]
@rbb-dev I know I did it to fast, this was just a way to easy reproduce. In my standard automation I do it every 60s it still happens but far less frequent so more difficult the get the exact logging. The effect however is the same.
Why do you expect it goes wrong if I do it this frequent? It does acknowledge each current setting.

**Reply by rbb-dev** [reply]
on my charger its little linux SoC is jumping to 80% CPU for up to 10-15 seconds when its processing rate changes as it tries to connect to gpios and so some magic.
in your logs I didn't see you setting up the 32A but charger just goes to it automatically.
Its definitely an issue on the charger side, but workaround is simple.
1 - for the duration of the charge, set the sample period to 10 seconds (if your charger can handle it) (example below)
2 - Monitor sensor.charger_ac_current_import (or whatever your charger name is)
3 - If it is 32, set it to whatever your other automations determine is available power.
4 - set the sample rate back to 60
Basically you will force the charger to go down to right Amps when it decides to to go crazy.
It's not elegant, but it's a workaround. A 10-second breach on a phase limit should be okay unless you have a smart circuit breaker, which will see the overload and trip


```
alias: Chager AC - Set Metering to 10 seconds during Solar charging
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.charger_ac_status_connector
    from: Preparing
    to: Charging
conditions:
  - condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.home_energy_gateway_solar_power
        above: 1
      - condition: time
        after: "08:00:00"
        before: "19:00:00"
        weekday:
          - sat
          - fri
          - thu
          - wed
          - tue
          - mon
          - sun
actions:
  - action: charger_ac.configure
    data:
      ocpp_key: MeterValueSampleInterval
      value: "10"
mode: single

```
