### DISCUSSION TITLE
Change sampling interval?

### DISCUSSION THREAD

**Discussion by APayerl** [lbbrhzn/ocpp#1532] [Q&A]
When I set up my charger (pre 0.8.0) I didn't touch the setting `Charger idle sampling interval (seconds)`, but that has since caused me quite some problems when trying to do automations based on the sensors that only update every 15 minutes…
Now I updated to 0.8.0 (and it works, woho! :D) but is there a way to change the sampling interval of an already created server?
Also, shouldn't this setting be part of the charger set up and not the server? Seems to me, it's more logical to set how often you want the charger to update its values rather to set it on the server?

**Comment by rbb-dev** [comment]
```
alias: 111 Test
description: ""
triggers: []
conditions: []
actions:
  - action: ocpp.configure
    data:
      ocpp_key: ClockAlignedDataInterval
      value: "15"
      devid: charger_dc
mode: single
```

This automation will work for you, I just tested it. This will force the charger to send Meter Values every 15 seconds while it is idle.
Whatever you're using this for, make sure to change it back to 900, the default.
