### DISCUSSION TITLE
Is there any way from a template or automation to discover the charger ID?

### DISCUSSION THREAD

**Discussion by BJReplay** [lbbrhzn/ocpp#1549] [Q&A]
I have a set of automations that (reasonably well - but it's work in progress) control my charger to charge using Excess Solar or flat out from the grid during a free power window.

In order to make these automations more generic, I'd like to replace references to my specific charger with generic equivalent.

My question is - other than already knowing the charger ID (e.g. sensor.<charger_id>_id gives me the charger ID as entered) can I retrieve the name of the entity from config?

This is, in a way, a more general question: Can automations access config, or only integrations?

I know that the config migration that we've all just gone through, the charger ID(s) are in the config - e.g.:
https://github.com/lbbrhzn/ocpp/blob/main/custom_components/ocpp/sensor.py#L46
and
https://github.com/lbbrhzn/ocpp/blob/main/custom_components/ocpp/__init__.py#L183

I'd like to ideally retrieve the charger ID(s) from an automation, so I can turn this into a template for sharing with our requiring much, if any configuration - especially for single charger installations.

For example, one of my snippets is 
``` yaml
conditions:
  - condition: or
    conditions:
      - condition: state
        entity_id: switch.sn10052312237994_charge_control
        state: "on"
      - condition: state
        entity_id: sensor.sn10052312237994_status_connector
        state: Charging
```

In a template, I can do this:

``` python
{% set charger_id = 'sn10052312237994' %}{% set current_import = charger_id ~ '_status_connector' %}
{% set status_connector = states.sensor[current_import].state %}
{{ status_connector }}
```

Which currently gives me "SuspendedEVSE".

I know I can do this in an automation:

``` yaml
variables:
  charger_id: '{{ ''sn10052312237994'' }}'
  status_connector_string: '{{ ''_status_connector'' }}'
  connector: '{{ charger_id ~ ''_status_connector'' }}'
  status_connector: '{{ states.sensor[connector].state }}'
  other_status_connector: '{{ states.sensor[charger_id ~ ''_status_connector''].state }}'
```

For this result:

``` text
context:
  id: 01JNN0B98TB6NACHHD377W47KW
  parent_id: 01JNN0B98SMYED14DDK1RVE738
  user_id: null
charger_id: sn10052312237994
status_connector_string: _status_connector
connector: sn10052312237994_status_connector
status_connector: SuspendedEVSE
other_status_connector: SuspendedEVSE
```

Or even (this would allow a single edit to allow the automation to be used with different charger IDs):

``` yaml
variables:
  charger_id: '{{ states(''sensor.sn10052312237994_id'') | lower }}'
  status_connector_string: '{{ ''_status_connector'' }}'
  connector: '{{ charger_id ~ ''_status_connector'' }}'
  status_connector: '{{ states.sensor[connector].state }}'
  other_status_connector: '{{ states.sensor[charger_id ~ ''_status_connector''].state }}'
```
