### DISCUSSION TITLE
Charging current limit with floating point / decimal number

### DISCUSSION THREAD

**Discussion by StefanLobbenmeier** [lbbrhzn/ocpp#1613] [Q&A]
The wiki suggests that current limit can only be a whole number, because the input is converted into int:
https://github.com/lbbrhzn/ocpp/wiki/Charge_automation#txprofile

Did someone try floating points / is this not possible by spec or are there issues with some devices?

**Comment by StefanLobbenmeier** [comment]
According to OCPP documentation 1.6 here  https://openchargealliance.org/my-oca/ocpp/

decimal values that are multiples of 0.1 are acceptable 
```json
                                "limit": {
                                    "type": "number",
                                    "multipleOf" : 0.1
                                },
```

**Reply by StefanLobbenmeier** [reply]
I just tried this automation and it was accepted by my wallbox:

```yaml
action: ocpp.set_charge_rate
data:
  custom_profile: |
    {
      "transactionId": {{ states('sensor.ebox_transaction_id') | int }},
      "chargingProfileId": 1,
      "stackLevel": 0,
      "chargingProfilePurpose": "TxProfile",
      "chargingProfileKind": "Relative",
      "chargingSchedule": {
        "chargingRateUnit": "A",
        "chargingSchedulePeriod": [
          {"startPeriod": 0, "limit": {{ states('input_number.evbox_charge_limit') | float | round(1) }}}  
        ]
      }
    }
  conn_id: 1
```
