### DISCUSSION TITLE
Stop transaction when suspended

### DISCUSSION THREAD

**Discussion by Strixx76** [lbbrhzn/ocpp#456] [Ideas]
Trying to get my head around this OCPP by reading the documention in the [OCPP Python Packeage](https://github.com/mobilityhouse/ocpp/tree/master/docs/v16), and at the same time looking in the source of this repository.

But I need to ask:
How do I end an transaction when the state of the connection is `SuspendedEVSE` or `SuspendedEV`?

I started using this integration yesterday, giving up on the Wallbox cloud service integration. I could see that my EV was charging with available power. But I noticed that after the battery was full it the status changed to `SuspendedEV` and afterwards it started to charge  with different intervals and with different power. I also noticed that the car was "on" as long as the transaction was ongoing. And since the charge control switch was off when the state was suspended I could not end the transaction.

Should the state of the switch not be off when the transaction is suspended?
Or should their be a button to be able to send a `StopTransaction.req`?

I don't want the car to be in on/idle the hole night consuming energy, and want to be able to end the transaction when the battery is full.
----------------------------------------------------------------------------
**EVSE:** Wallbox Pulsar Plus (model: PLP1-M-2-4) (firmware: 5.5.10)
**EV:** MG ZS EV (2020)
**OCCP ver:** 0.4.26
**HA ver:** 2022.2.6

**Comment by GrantKeymer** [comment]
I think this might be an issue with your MG.  My Nissan Leaf starts tapering the charging power when the battery is almost full.  It reduces right down to 0.4kW with a short time at 0 then 0.4kW again, repeating in a cycle, before finally stopping with status `SuspendedEV`.  After that, the status remains the same for as long as the EV is plugged in.

However, I agree, you need to have some way to end the charging session under these conditions.  No doubt one of the other contributors will be along soon with some ideas.

**Comment by drc38** [comment]
You can turn on the Availability switch to stop the transaction, or unplug the car.

**Reply by Strixx76** [reply]
No. If I try to do that I get: "Warning: Set availability failed with response Scheduled".

Of course I can unplug the car. But the purpose of automation is that I shouldn't need to do it... ;-)
I want to be able to write an automation that ends the transaction when the car have suspended the chargeing for lets say more than 30 minutes.

**Comment by lbbrhzn** [comment]
A remote stop transaction should do the trick. There should be a service defined for it, but it appears to be missing from services.yaml. @drc38, can you double check?

**Reply by mazzy89** [reply]
@lbbrhzn there is no remote_stop_transaction in the `service.yaml`. 

> Ah, the remote_stop_transaction should be sent when you flip the Charging switch off

Can you advice here how it could be sent the `RemoteStopTransaction`?  Should we use the `data_transfer` service?

**Comment by lbbrhzn** [comment]
Ah, the remote_stop_transaction should be sent when you flip the Charging switch off.  Note that is will leave the charger in finalizing state until unplugged.

**Reply by Strixx76** [reply]
But the switch is already in off when the charging is suspended. So there is no way to flip it.

**Reply by drc38** [reply]
Even though it is off try calling the service `switch.turn_off` from the Developer tools and see if that works

**Reply by drc38** [reply]
I've added the extra two states in #459 so you can turn it off from the interface

**Comment by mazzy89** [comment]
@Strixx76 have you achieved what you were trying to do?

**Reply by Strixx76** [reply]
Totally forgot about this. I never continued with my own automation. Instead I started to use the [EV Smart Charging](https://github.com/jonasbkarlsson/ev_smart_charging) integration to control my charging sessions. But I guess it works now because I can't remember ever seeing the charging session on after the planned time. The EV Smart Charging integration is controlling the OCPP integration.

**Reply by mazzy89** [reply]
Right but that integration seems only suitable for scandinavian people. Not my case unfortunately.

**Reply by Strixx76** [reply]
Well, it needs hourly price data. But it can get from different integrations. One of them is [ENTSO-e Transparency Platform Energy Prices](https://github.com/JaccoR/hass-entso-e) which says: _"fetch energy prices of all European countries from the ENTSO-e Transparency Platform"_ So I guess you at least has to be in Europe to benefit from it.

**Reply by mazzy89** [reply]
That platform does not give correct data. Those data are not per local european provider they are just average calculate in the country. Not very reliable way.

**Reply by Strixx76** [reply]
Aha. That is unfortunate.

Any way, looking at the source for the EV Smart Charging integration it does use the service call switch.turn_off to stop the transaction. So you should be able to use it in your automation.

**Reply by mazzy89** [reply]
Thanks @Strixx76. Actually I have found that the binary sensor coming with the integration works like a charm. Here I post my automation for the future generation that will look for an automated way to start/stop the charging session

```yaml
- id: start_charging_tesla
  alias: Start charging Tesla
  trigger:
    - platform: state
      entity_id: binary_sensor.tesla_plugged_in
      from: "off"
      to: "on"
  condition:
    condition: and
    conditions:
      - alias: "Tesla is at home"
        condition: zone
        entity_id: device_tracker.modely
        zone: zone.home
      - alias: "Charger is available"
        condition: state
        entity_id: sensor.charger_status_connector
        state: "Available"
  action:
    - service: switch.toggle
      target:
        entity_id: switch.charger_charge_control
  mode: single
```
