### DISCUSSION TITLE
Unlock failed with response NotSupported

### DISCUSSION THREAD

**Discussion by maciii** [lbbrhzn/ocpp#472] [Q&A]
Hi, I just installed Wallbox Pulsar Plus (SW 5.5.11, 1 phase, 16A max). Workes good. Then I setup OCPP in HA - connected to OCPP ok, but now it is locked. 

![image](https://user-images.githubusercontent.com/20968278/161288124-617786c1-332d-434b-9b1c-5c7a25ae2caf.png)

So now I can't use Wallbox App anymore? Correct?

When I try switch ON Charge_Control in HA or pressing switch .Unlock I have error message:

OCPP integration Warning: Unlock failed with response NotSupported.

During configuration I checked ALL OCCP Measurands

Any help please?

**Comment by maciii** [comment]
EDIT:  I removed ws:// behind IP address. Now when I press Charge_Control to ON it unlocks charger and it changed switch Availability to OFF. After some time it locks again. Is it purpose? To automatically lock charger without connecting car?

All this steps I made without car connected.

**Comment by lbbrhzn** [comment]
@macii, this is expected behavior of the Wallbox pulsar plus. In OCPP mode the wallbox portal will report the status 'Locked', but in Home Assistant it will be 'Available' until a car is connected, then it becomes 'Preparing'. You then need to flip the charge control switch to 'On' to start charging. That will send a 'RemoteStartTranaction.Req' message to the charger, and the status becomes ' Charging'. You can use an automation to flip the switch automatically.

BTW, the Unlock switch sends an UnlockConnector.req message. The purpose of this message is to help EV drivers that have problems unplugging their cable from the Charge Point in case of malfunction of the Connector cable retention.

**Comment by lbbrhzn** [comment]
Here's the automation I use:

```
alias: Start charging
description: Start charging when status is preparing
trigger:
  - platform: state
    entity_id: sensor.pulsar_status_connector
    to: Preparing
    for:
      hours: 0
      minutes: 0
      seconds: 10
condition: []
action:
  - type: turn_on
    device_id: 3b417e9ace811d1450610f07ae2671ae
    entity_id: switch.pulsar_charge_control
    domain: switch
mode: single
```

The device id the ocpp charge point entity, which I have named 'pulsar'.
