### DISCUSSION TITLE
Ocular IQ Wallbox - Working

### DISCUSSION THREAD

**Discussion by kwanm84** [lbbrhzn/ocpp#789] [General]
Just thought I'd post, I have an australian charger, the Ocular IQ Wallbox (https://ocularcharging.com.au/ocular-iq-wallbox/) - IOCAH10-22S

Ocpp works well... the following sensors are functioning;

Energy.Active.Import.Interval
Energy.Active.Import.Register
Energy.Meter.Start
Energy.Session
Power.Active.Import
Time.Session
Transaction.Id

Controls:
charger.Reset
charger.Unlock
Availability
Charge_Control
Maximum_Current

Diag:
Connectors
Error.Code
Error.Code.Connector
Profiles.AUTH|REM|RES|SMART|FW|CORE
Heartbeat
2 hours ago
ID
Id.Tag
Latency.Ping
Latency.Pong
Model
Reconnects
Serial
Status
Status.Connector
Stop.Reason
Timestamp.Config.Response
Vendor
Version.Firmware
22103101-22050701-22050701

-----

Note: For me... on 3 phase... setting maximum current below 6 will stop all charging. I guess a limit in the charger. It will charge upto 15 amps (limited 11kw by car). Don't have a compatible ev to test 32 amps.

**Comment by iJuiceman** [comment]
Hi mate, I also have the Ocular IQ Solare and have it connected and working with HA.
One thing I am not sure what is wrong, is that none of my sensors are showing data, they are all showing unknown.
Sensors:
Energy Active Import Register
Energy Meter Start
Energy Session
Time Session
Transaction ID 

Any ideas ?

Everything else is working fine.

**Comment by kwanm84** [comment]
Not sure what is extra in the solar. I assume it has ct clamps and can self
manage itself.

I use "charger maximum amps" and my solar goes through ha. So I use ha to
manage the charging when I have excess solar. It's a little complicated but
works well.

I have all the sensors you listed. If you still get some info and can
control it then I assume it setup correctly. As for missing sensors...
honestly no idea.

Can you manual change Max amps and availability / charge control?

I'm away from home for another 3 days so I can't help much until I'm back.

**Comment by bradmatt275** [comment]
Out of curiosity does this prevent the app from working?

I just got this charger installed myself. I can see the option to set the OCPP endpoint. It's currently pointing at ocpp.ocularcharging.com.au which makes me think it's required for the app.

**Reply by kwanm84** [reply]
I would assume it does prevent the app from working. I assume the app is free, but you pay for the OCPP service ocular provide? I've only ever run my own server so never needed the app.

**Reply by bradmatt275** [reply]
I figured that might unfortunately be the case. It's the Ocular Smart Home app which is free. 

I might just have to decide between the two. HA would be amazing but I don't think it lets you control the solar charging profile like the app does.

I appreciate the reply. Thank you.

**Reply by kwanm84** [reply]
Yea, I had a go at adding my charger to the app, but it couldn't find it, so confirmed won't work.

I do have my charger running purely off solar with my HA. It definitely not easy to setup as I have batteries as well, and I wanted to make sure it didn't charge off them... obviously you need all your energy stats... at a minimum, solar and house usage. Needs a few work arounds with automations to make it run well. But should work as well as the app (if not better) with some effort.

I see how much excess energy I produce... this is a little complicated with my setup as I want the battery to always charge 2.5kw until its full

then set the amps for the charger based on that, and adjust it every 30 seconds. 

e.g. <4kw - 0 amps
4-4.4kw - 6 amps 
...
10.7-10.9kw - 16 amps
>10.9kw - 32 amps

This is for 3 phase.

But it does work really well... I can override it and tell it to charge off the grid.

I don't have functions such as start and end timers, or charge a specific amount of energy... but I really don't need it with the setup I have. It will always charge off solar... avoid charging between 4pm and 8pm on weekdays (we have demand charges in QLD)... or I can override to charge off grid... and even during the demand time if I really need charging.

These are my current stats, I don't think we've used the grid for months.

Total EV Charge: 2941.54 kWh
Charge from Solar: 87.51% (2574.11 kWh)

**Reply by bradmatt275** [reply]
Amazing. I never thought of doing that. Sounds like I could have saved some money by getting the regular one (without the CT clamp).

I'll have a play around and see if I can replicate your setup. I have my inverter connected to HA through their API. The data is a little delayed but not too bad.

Thanks again for all that info.

**Reply by Surk91** [reply]
I know it's been a while, but has anyone here found a fix for this reset issue? I've been trying to connect mine to HA today and it did the reset and dropped all the settings and reverted back to "N/A" for the SN/model/vendor fields which are now grey for some reason. I briefly had the charger come up in the OCPP integration and then everything went to unavailable like the posters above.

**Reply by dsmackie** [reply]
> I know it's been a while, but has anyone here found a fix for this reset issue? I've been trying to connect mine to HA today and it did the reset and dropped all the settings and reverted back to "N/A" for the SN/model/vendor fields which are now grey for some reason. I briefly had the charger come up in the OCPP integration and then everything went to unavailable like the posters above.

The issue is within the OCPP app within the charger. It has a bug where it can only accept a finite length response from the HA OCPP agent. When it receives a response that is larger than it can handle, there is an error and the string HA sent overwrites memory where the charger config is stored. The charger then saves this "garbage" into the settings config, and on next reboot the settings are corrupt so it loads up a default setting file. This default setting file does not have any details specific to your charger, so S/N, model, vendor etc are now lost.

I raised an issue with both Ocular and the Chinese manufacturer whom which Ocular just re-badge with no joy.

Do you have the details of the S/N, model and vendor from the box or sticker on the unit? I am fairly sure at the moment your unit is bricked with the lose of these settings. If you know the S/N, etc, I can probably help you craft a command to send to your unit to re-populate these details and unbrick it. I had to do this with mine, but I was fortune to have a good set of values from a previous session of trying to "fix" it.

**Reply by StroppyOz** [reply]
> Do you have the details of the S/N, model and vendor from the box or sticker on the unit? I am fairly sure at the moment your unit is bricked with the lose of these settings. If you know the S/N, etc, I can probably help you craft a command to send to your unit to re-populate these details and unbrick it. I had to do this with mine, but I was fortune to have a good set of values from a previous session of trying to "fix" it.

@dsmackie I have these details. If you're still happy to help craft a command to repopulate these fields, I'm happy to be the guinea pig.

**Comment by iJuiceman** [comment]
I worked out its HA or the App, not both.  I contacted OcularIQ, but have not had a reply from them about the ability to poll their API for the details, so I can put it into HA.  Having used the charger for a few months, I think I will scrap the App and just use HA with the OCPP plugin

**Comment by jay510-dev** [comment]
Sorry for digging up an old thread - how did you manage to get the Ocular talking to HA? I've tinkered with the setup page with no luck - should I be changing the server path or identity? 

![image](https://github.com/lbbrhzn/ocpp/assets/73097611/9be4b24c-69b0-46ee-ba49-69530d39ccd7)

**Comment by MikeatLorne** [comment]
for domain: use the ip of your hass
server port: 9000
server path: /

that should then show a "reference url" at the bottom - fine is: ws://192.168.86.110:9000/Alkdsfajdjldf

**Comment by MikeatLorne** [comment]
I am having trouble getting the sensors working  - fine for 10 months but has not worked for about 4 weeks now.  I am unable to track it to anything I have done: Controls and some information is coming through okay

I am getting this in debug files (sample): 

2023-12-26 15:39:02.005 DEBUG (MainThread) [custom_components.ocpp] 'A14223215317' trying measurand 'Energy.Reactive.Import.Register'
2023-12-26 15:39:02.005 INFO (MainThread) [ocpp] A14223215317: send [2,"4da1b115-d5b1-42a1-9b18-7a9a1c67aa6f","ChangeConfiguration",{"key":"MeterValuesSampledData","value":"Energy.Reactive.Import.Register"}]
2023-12-26 15:39:02.105 INFO (MainThread) [ocpp] A14223215317: receive message [3,"4da1b115-d5b1-42a1-9b18-7a9a1c67aa6f",{"status":"RebootRequired"}]

any ideas?

**Comment by julianjwong** [comment]
I'm trying to get my Ocular Solar IQ connected and wondering if there's any extra settings needed other than the path and HA IP address via the Ocular installer config portal? Mine appears to connect briefly with HA and displays some updates to sensors in HA which tells me the comms partly works. But then within about a minute everything goes Unavailable. The charger beeps quite a few times as this happens. Is there anything specific I need to do in the OCPP integration? Any help or ideas appreciated!

**Reply by julianjwong** [reply]
![Screenshot_20240326_223000_Home Assistant](https://github.com/lbbrhzn/ocpp/assets/32351689/4facb852-eef2-446c-9f49-c2b39226a5a4)
Managed to screenshot before it went unavailable

**Reply by bradmatt275** [reply]
I ended up giving up on mine. It kind of did the same thing as yours where it would reboot and one time it even factory reset the device.

I suspect it has something to do with the energy management component of the Solar IQ. 

If I had to guess id say it's getting conflicting instructions from the HA OCPP and the energy management OCPP causing it to freak out.

**Reply by dsmackie** [reply]
> I ended up giving up on mine. It kind of did the same thing as yours where it would reboot and one time it even factory reset the device.

Just so you know you are not crazy, mine did the same as yours and factory reset today. I changed the OCPP settings to talk to HA and all settings reset to N/A or defaults. I was fortunate to have a tab open with the Web UI and could reapply the previous settings.

The issue (100% the charger) comes from this HA OCPP module performing checks to determine the available measurands. It sends each measurand individually to the charger to verify it can provide the required details and builds a final list of all measurands. Once the final list is known, that is sent to the charger to set all the measurands that should be returned. The charger has an issue where the list provided is too big and it craps out. The result is a factory reset.

I've reached out to the OEM for the charger to report this issue and just waiting on a response.

**Reply by bradmatt275** [reply]
> > I ended up giving up on mine. It kind of did the same thing as yours where it would reboot and one time it even factory reset the device.
> 
> Just so you know you are not crazy, mine did the same as yours and factory reset today. I changed the OCPP settings to talk to HA and all settings reset to N/A or defaults. I was fortunate to have a tab open with the Web UI and could reapply the previous settings.
> 
> The issue (100% the charger) comes from this HA OCPP module performing checks to determine the available measurands. It sends each measurand individually to the charger to verify it can provide the required details and builds a final list of all measurands. Once the final list is known, that is sent to the charger to set all the measurands that should be returned. The charger has an issue where the list provided is too big and it craps out. The result is a factory reset.
> 
> I've reached out to the OEM for the charger to report this issue and just waiting on a response.

I would be interested to see if they fix it. Their support was pretty good and did their best to help me, but I wasn't impressed with the charger.

Had so many issues where it would just stop charging for no reason. When the charger was bricked after a firmware update it was the final straw.

I ended up getting a partial refund and buying a Zappi to replace. I've been super happy with the Zappi. It just works and was really easy to add into HA.

**Reply by dsmackie** [reply]
> I would be interested to see if they fix it. Their support was pretty good and did their best to help me, but I wasn't impressed with the charger.
> 
> Had so many issues where it would just stop charging for no reason. When the charger was bricked after a firmware update it was the final straw.
> 
> I ended up getting a partial refund and buying a Zappi to replace. I've been super happy with the Zappi. It just works and was really easy to add into HA.

I've only had the charger for 48hrs so cannot make any concrete reviews, but the app does not fill me with much hope. The solar only feature seems to just sit at "Suspended" and never actually charges. Unsure if I have a CT clamp backwards or some config needs to change. Still looking at it all to try and figure out how best to use it.

I think controlling via HA will be best, if they can fix the OCPP issues. I have gone direct to the manufactures who make the device in China. Unsure if I would have any joy through the Australian retailed who is just rebranding the device with their own cover plate.

If I ever hear anything I'll throw up an update.

**Reply by bradmatt275** [reply]
> > I would be interested to see if they fix it. Their support was pretty good and did their best to help me, but I wasn't impressed with the charger.
> > Had so many issues where it would just stop charging for no reason. When the charger was bricked after a firmware update it was the final straw.
> > I ended up getting a partial refund and buying a Zappi to replace. I've been super happy with the Zappi. It just works and was really easy to add into HA.
> 
> I've only had the charger for 48hrs so cannot make any concrete reviews, but the app does not fill me with much hope. The solar only feature seems to just sit at "Suspended" and never actually charges. Unsure if I have a CT clamp backwards or some config needs to change. Still looking at it all to try and figure out how best to use it.
> 
> I think controlling via HA will be best, if they can fix the OCPP issues. I have gone direct to the manufactures who make the device in China. Unsure if I would have any joy through the Australian retailed who is just rebranding the device with their own cover plate.
> 
> If I ever hear anything I'll throw up an update.

Oh yeah I had that problem. Might be unrelated, but if it helps, that happened to mine because the safe current limit was setup incorrectly.

It's actually the reverse to what you think it would be. I thought it needed to be the max current allowed so it doesn't trip the breaker (e.g. 28.8 amps for a 32 amp circuit). But turns out it's actually the reverse. You need to enter 3.2 amps instead.

**Comment by vicinigit** [comment]
I'm using the Ocular IQ and can control it fairly well with Home Assistant using OCPP integration. Issues I'm keen to get help with are:

1. I don't know what "Availability" does. It's usually false (but everything still works) and if I set it to true it just switches itself back to false
2. The sensors don't seem to update quickly at all. Lags of hours is not uncommon. Any ideas how to force an update?

**Reply by vicinigit** [reply]
Ok #1 was easy. Availability is true when the charger in not being used.
#2 is still an open question.

**Reply by bradmatt275** [reply]
You can try using a REST integration in HA.

I don't have my Solar IQ anymore. It was bricked after a firmware update and I returned it.

But back when I had it running I ended up making HTTP calls:

<img width="554" alt="image" src="https://github.com/user-attachments/assets/a2e07b42-7dcc-48e4-94c0-c32c46941bc0" />

<img width="939" alt="image" src="https://github.com/user-attachments/assets/cf6c69a9-5d0e-49f9-8274-2afada4517cc" />

You can then setup something like this in HA:

```
rest:
  - resource: http://192.168.2.64/cgi-bin/action.exe
    username: !secret car_charger_username
    password: !secret car_charger_password
    authentication: basic
    method: POST
    payload: '{"action":"statistics","data":"ModbusMaster"}'
    scan_interval: 30
    sensor:
      - name: "Car Charger Mode"
        value_template: >
          {% set outer_json = value_json %}
          {% set inner_json = outer_json.data | from_json %}
          {{ inner_json.ecoMode }}

      - name: "Power Grid Current"
        unique_id: sensor.power_grid_current
        unit_of_measurement: 'A' 
        device_class: "current"
        value_template: >
          {% set outer_json = value_json %}
          {% set inner_json = outer_json.data | from_json %}
          {{ inner_json.sampledValue.powerGrid[0].current[0] }}

      - name: "Power Grid Voltage"
        unit_of_measurement: 'V'
        device_class: "voltage"
        unique_id: sensor.power_grid_voltage
        value_template: >
          {% set outer_json = value_json %}
          {% set inner_json = outer_json.data | from_json %}
          {{ inner_json.sampledValue.station[0].conns[0].voltage[0] }}
```

It actually worked really well for me.

There are other things you can get from that but those were the ones I was interested in at the time.

**Comment by julianjwong** [comment]
Thanks for sharing the REST approach.
Not working for me unfortunately.

I'm getting this error

{
  "code": 1004,
  "message": "NO FOUND \/tmp\/Ioc\/ModbusMaster.json",
  "data": null
}

**Reply by bradmatt275** [reply]
Do you have the Solar IQ or the one without a CT clamp?

I think that ModbusMaster log only works for the Solar one.

But it you go into the WebUI (on the Ocular) and open the individual logs. You can see the HTTP calls that are being made via the Chrome devtools.

You might be able to do some poking around and see which ones your unit supports.

**Reply by julianjwong** [reply]
Thanks for the tip.
So if I send METER then it returns

{
  "code": 200,
  "message": "Success",
  "data": "[{\n\t\t\"meterFault\":\tfalse,\n\t\t\"meterData\":\t{\n\t\t\t\"vol\":\t[2199, 0, 0],\n\t\t\t\"cur\":\t[305, 0, 0],\n\t\t\t\"power\":\t[6773, 0, 0, 0],\n\t\t\t\"Q\":\t[0, 0, 0, 1533617],\n\t\t\t\"ticks\":\t398962290\n\t\t}\n\t}]"
}


Is this what you were getting back? Is there a way to trigger start charging or stop charging?

**Reply by bradmatt275** [reply]
Not with HTTP unfortunately (that I'm aware of). This was just to get around the slow sensor refresh.

But you could use REST to read the sensors and OCPP to trigger charging.

**Reply by julianjwong** [reply]
Unfortunately OCPP integration still isn't working for me. Tried again after nearly another year and several updates but still the same issue. It does appear to load some more values initially but then drops and becomes unavailable. Will stick with the mobile app and manually triggering. Annoying as I wanted to automate current limits based on solar (my solar setup is only 5kw and the CT clamp couldn't be installed due to a long cable run).

**Reply by bradmatt275** [reply]
Dam, well you could try something like this:

<img width="630" alt="image" src="https://github.com/user-attachments/assets/31ce8182-103f-45ec-b000-ccc8e6337191" />

I actually did get it working but I was a bit hesitant to use it. It was more of a test case.

When you save a setting in the WebUI you can see it calls this endpoint with the full JSON payload.

But I found you can just send individual properties like the EcoMode. Which from what I found is the charging mode.

**Reply by julianjwong** [reply]
Thanks for the pointers. I haven't done any web development so all of this is new to me. I'm familiar with the concepts but need to spend some time upskilling. I'll have a play around and see what I can learn from the logs and payloads. Definitely worth it for me in the long run as I currently get free electricity between 12-2pm so I want my charger to run at full 32amp then and throttle back to whatever my solar excess is at other times. Looks like I'll have to go down a full custom route given ootb OCPP is a no go for me and I can't take advantage of some of the other solar charging integrations others have already developed.

**Reply by dsmackie** [reply]
> Unfortunately OCPP integration still isn't working for me. Tried again after nearly another year and several updates but still the same issue. It does appear to load some more values initially but then drops and becomes unavailable. Will stick with the mobile app and manually triggering. Annoying as I wanted to automate current limits based on solar (my solar setup is only 5kw and the CT clamp couldn't be installed due to a long cable run).

The installation manual for the IQ Solar reads that the CT clamp can be extended further than the provided 20m with Cat5 cable. Unsure if this helps you out at all.

**Reply by julianjwong** [reply]
Thanks but too late now. The sparkies I used were subcontractors of the EV charging company and had no clue. Would have needed them to do the cable run at the same time they ran a new cable for the charger.

But given I'm only on a 5kw solar inverter, the Solar IQ standard solar charging functionality would be pretty useless as it's geared up for larger solar arrays.

**Reply by julianjwong** [reply]
Sorry maybe the wrong place to ask but it's related to fetching data via RESTFUL in Home Assistant from the Ocular endpoint.

I can't seem to grab the values into sensors as the logs show the values include the newline and tab delimiters with \t\n which I think is screwing up the parsing?

Any ideas?

**LOG Excerpt:**

```
2025-01-13 14:17:45.183 DEBUG (MainThread) [homeassistant.components.rest.data] Updating from http://192.168.0.92/cgi-bin/action.exe
2025-01-13 14:17:45.231 DEBUG (MainThread) [homeassistant.components.rest] Finished fetching rest data data in 0.048 seconds (success: True)
2025-01-13 14:17:45.233 DEBUG (MainThread) [homeassistant.components.rest.data] Data fetched from resource: {
	"code":	200,
	"message":	"Success",
	"data":	"[{\n\t\t\"connType\":\t\"TYPE2(AC)\",\n\t\t\"runState\":\t\"AC_Idle\",\n\t\t\"errCode\":\t0,\n\t\t\"outputCur\":\t[0, 0, 0],\n\t\t\"outputVol\":\t[2399, 0, 0],\n\t\t\"offerCur\":\t0,\n\t\t\"offerVol\":\t0,\n\t\t\"connStatus\":\t\"Unplug\",\n\t\t\"unit\":\t\"W\",\n\t\t\"outLimit\":\t0,\n\t\t\"tmpUnlock\":\tfalse,\n\t\t\"info\":\t{\n\t\t\t\"smartAdjCurrent\":\t0,\n\t\t\t\"pwmPercent\":\t1000,\n\t\t\t\"CP\":\t\"A\",\n\t\t\t\"CC\":\t\"63A\"\n\t\t}\n\t}]"
}
```

**Configuration.yaml excerpt:**
```
rest:
  - resource: http://192.168.0.92/cgi-bin/action.exe
    username: admin
    password: mypassword
    authentication: basic
    method: POST
    payload: '{"action":"statistics","data":"CONNECTOR"}'
    scan_interval: 30
    sensor:
      - name: "EV Car Charger JSON response"
        unique_id: sensor.ev_car_charger_json
        value_template: "{{ value_json.message }}"
        
      - name: "EV Car Charger JSON data"
        unique_id: sensor.ev_car_charger_json_data
        value_template: "{{ value_json.data }}"
        
      - name: "EV Car Charger Status"
        unique_id: sensor.ev_car_charger_status
        value_template: "{{ value_json.data[0].runState }}"
        
      - name: "EV Car Charger Plug Status"
        unique_id: sensor.ev_car_charger_plug_status
        value_template: "{{value_json.data[0].connStatus}}"

      - name: "EV Charging Current"
        unique_id: sensor.ev_car_charger_current
        unit_of_measurement: 'A' 
        device_class: "current"
        value_template: "{{ value_json.data[0].outputCur[0] | int / 10 }}"

      - name: "EV Car Charger Voltage"
        unit_of_measurement: 'V'
        device_class: "voltage"
        unique_id: sensor.ev_car_charger_voltage
        value_template: "{{ value_json.data[0].outputVol[0] | int / 10 }}"


```
