### DISCUSSION TITLE
option to disable HA notifications from Ocpp integration

### DISCUSSION THREAD

**Discussion by oraveczt** [lbbrhzn/ocpp#938] [Show and tell]
This is not an operational problem, however it's quite frustrating that my ABB wall charger triggers "Security event notification received: SettingSystemTime" kind of notifications in Home Assistant on a daily basis.

I could not figure out how to mute these.

Can you add some sort of config options to the Ocpp integration to be able to mute these kind of notifications?

Thanks in advance :)

**Comment by drc38** [comment]
Simply create an automation eg
```
trigger:
  - platform: persistent_notification
    update_type:
      - added
    notification_id: ""
condition:
  - condition: template
    value_template: "{{ trigger.notification.title | lower == \"ocpp integration\" }}"
action:
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: persistent_notification.dismiss
    data:
      notification_id: "{{ trigger.notification.notification_id }}"
mode: parallel
max: 10
```

**Reply by oraveczt** [reply]
Thank you so much! This script works like a charm. No more annoying OCPP notifications! Excellent work.

**Reply by ohadbenita** [reply]
For some reason this stopped working a while ago (currently on 2025.6.3). Any chance anyone else ran into this and managed to solve it?

**Reply by alfiriel** [reply]
Hi, this one works for me HA Core 2026.3.4

```
alias: OCPP Integration Benachrichtig
description: >-
  Lösche die Benachrichtigung, die beim Neustart von HA von der OCPP Integration
  erstellt wird.
triggers:
  - update_type:
      - added
    trigger: persistent_notification
conditions:
  - condition: template
    value_template: >
      {{ trigger.notification.title | default("") | lower == "ocpp integration"
      }}
actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - data:
      notification_id: "{{ trigger.notification.notification_id }}"
    action: persistent_notification.dismiss
mode: parallel
max: 10
```
