### DISCUSSION TITLE
Home Assistant page showing all charges including the charged kWh and the price. Still ugly behind the UI though ^^

### DISCUSSION THREAD

**Discussion by dreimer1986** [lbbrhzn/ocpp#943] [Show and tell]
So, first some backstory. My EVBox Elvi has no electricity meter included (yet) and thus most values I can get regarding electricity are 0 by now. This will change soon as the first box of two in our family was already converted to the more expensive model WITH meter inside. It works like a charm in a quick test in this addon and as soon as I have mine modified, too I will post the result in my (closed) report I sometimes fill with new stuff. https://github.com/lbbrhzn/ocpp/issues/221
I only will get this changed if I change to some charge controlling service was the first thing I was told. Why? It's not really MY wallbox tbh ^^ Anyways I was told that some externally available CSV downloads would be fine already. So this was the first thing I did. 

Now for my showoff with some ugliness and hopefully some suggestions from you all.

automations.yaml:
```
- id: ocppsession1
  alias: OCPP session 1
  trigger:
  - platform: state
    entity_id: sensor.evbox_status_connector
    to: Available
  condition:
  - condition: template
    value_template: "{{ trigger.from_state is not none and trigger.from_state.state not in ['unknown','unavailable'] }}"
  - condition: state
    entity_id: sensor.evbox_id_tag
    state: '04B36F3AE56280'
  action:
  - service: notify.ocppexport1
    data_template:
      message: '{{now().strftime("%d.%m.%Y")}};{{now().strftime("%H:%M:%S")}};{{ states.sensor.evbox_time_session.state}};{{ states.sensor.evbox_id_tag.state}};{{ states.sensor.sessionenergy.state}}'
  - service: shell_command.loadocppcsv
  mode: single
- id: ocppsession2
  alias: OCPP session 2
  trigger:
  - platform: state
    entity_id: sensor.evbox_status_connector
    to: Available
  condition:
  - condition: template
    value_template: "{{ trigger.from_state is not none and trigger.from_state.state not in ['unknown','unavailable'] }}"
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.evbox_id_tag
      state: '04B36F3AE56280'
  action:
  - service: notify.ocppexport2
    data_template:
      message: '{{now().strftime("%d.%m.%Y")}};{{now().strftime("%H:%M:%S")}};{{ states.sensor.evbox_time_session.state}};{{ states.sensor.evbox_id_tag.state}};{{ states.sensor.sessionenergy.state}}'
  - service: shell_command.loadocppcsv
  mode: single
- id: ocpp_csv_load
  alias: OCPP CSV Load
  trigger:
    - platform: homeassistant
      event: start
  condition: []
  action:
    - delay: '00:01:00'
    - service: shell_command.loadocppcsv
- id: ocpp_set_midnight
  alias: OCPP Midnight Update
  description: ''
  trigger:
  - platform: time
    at: "00:00:00"
  condition: []
  action:
  - service: shell_command.loadocppcsv
  mode: single
```

configuration.yaml:
```
notify:
  - name: ocppexport1
    platform: file
    filename: www/ocppexport1.txt
  - name: ocppexport2
    platform: file
    filename: www/ocppexport2.txt
```

This creates two CSV files. Both available from external by https://externaldomain.tld/local/ocppexport1.txt or ocppexport2.txt. One if I use my ID key and one if any other is used. That is still WIP as I don't know the ID of the 2nd key yet. Planned are two separate CSV for me and later my brother, too. Ignore the "- service: shell_command.loadocppcsv" for now. This will come later.
This results in nice CSV files that I hand edited for validity. Line 1 had a line like "Made from Home Assistant at..." and that I replaced with "date;time;sessiontime;token;charged" to make this thing really a csv file.

In theory this was all that was asked for, but I was on fire and wanted to see how far I can get that. Thus I looked for a nice custom addin for list support in HA and found this one: https://github.com/iantrich/list-card 

But I had a csv and this thing wanted a sensor... the HA community forums were the savior in this case: https://community.home-assistant.io/t/reading-multiple-rows-from-csv/326335

I heavily extended the script to make things for two separate data streams, ONLY for the charge sessions of the current month instead of 30 days and some calculation work, too:

ocpp_ui.py:
```
import csv
from datetime import date
from datetime import datetime
from datetime import timedelta
import requests

csv_file1 = "/config/www/ocppexport1.txt"
csv_file2 = "/config/www/ocppexport2.txt"
url = 'http://homeassistant.local:8123/api/states/sensor.'
days = int(date.today().strftime("%d"))

headers = {
    'Authorization': 'Bearer %TOKEN%',
    'content-type': 'application/json'
}

# Read the csv_file
csv_reader1 = csv.DictReader(open(csv_file1), delimiter=';')

the_list1 = []
kwh_list1 = []

for line in csv_reader1:
    tempdate = datetime.strptime(line['date'], '%d.%m.%Y')
    deltaMonth = timedelta(days=int(date.today().strftime("%d")))
    deltaToday = date.today() - tempdate.date()
    if deltaToday < deltaMonth:
        the_list1.append(line)
        kwh_list1.append(float(line['charged']))

# Revert the list, we want the last row at the top
the_list1.reverse()
kwh_list1.reverse()

# Read the csv_file
csv_reader2 = csv.DictReader(open(csv_file2), delimiter=';')

the_list2 = []
kwh_list2 = []

for line in csv_reader2:
    tempdate = datetime.strptime(line['date'], '%d.%m.%Y')
    deltaMonth = timedelta(days=int(date.today().strftime("%d")))
    deltaToday = date.today() - tempdate.date()
    if deltaToday < deltaMonth:
        the_list2.append(line)
        kwh_list2.append(float(line['charged']))

# Revert the list, we want the last row at the top
the_list2.reverse()
kwh_list2.reverse()

errors = ''

variable1 = 'ocpp1_energy'
variable2 = 'ocpp2_energy'
attributes1 = '{"unit_of_measurement": "kWh", "device_class": "energy", "friendly_name": "Daniel", "entries": ' + str(the_list1) + '}'
attributes2 = '{"unit_of_measurement": "kWh", "device_class": "energy", "friendly_name": "Andere", "entries": ' + str(the_list2) + '}'

data1 = '{"state": "' + str(sum(kwh_list1)) + '", "attributes": ' + attributes1 + '}'
data1 = data1.replace("'",'"')

data2 = '{"state": "' + str(sum(kwh_list2)) + '", "attributes": ' + attributes2 + '}'
data2 = data2.replace("'",'"')

r1 = requests.post(url+variable1, data=data1, headers=headers)
if r1.status_code != 200 and r1.status_code != 201:
    errors = errors + 'ERROR:' + variable1 + ' - ' + str(r1.status_code)

r2 = requests.post(url+variable2, data=data2, headers=headers)
if r2.status_code != 200 and r2.status_code != 201:
    errors = errors + 'ERROR:' + variable2 + ' - ' + str(r2.status_code)

if errors != '':
    print(errors)

```

This script is a MESS I know, but it works as it seems. This is where "- service: shell_command.loadocppcsv" comes in. It runs in four cases, the four already shown above. Otherwise the temporary sensors I made with the API would be gone or be outdated.

configuration.yaml:
```
shell_command:
  loadocppcsv: python3 ocpp_ui.py
```

Now I made a new space on Lovelace and threw two of these in there:

```
type: custom:list-card
entity: sensor.ocpp1_energy
title: Letzter Monat (Daniel)
feed_attribute: entries
columns:
  - title: Datum
    field: date
    style:
      - text-align: left
  - title: Uhrzeit
    field: time
    style:
      - text-align: right
  - title: Sitzungsdauer (min)
    field: sessiontime
    style:
      - text-align: right
  - title: Geladen (kWh)
    field: charged
    style:
      - text-align: right
```

One for "sensor.ocpp1_energy" and one for "sensor.ocpp2_energy". While we are at it I added a Glances tile with sensor.ocpp1_energy
and sensor.ocpp2_energy shwoing the kWh charged in this month. Now for the cost... I first hoped that I can get them off the energy settings already inside HA, but nope, so I made things quick and dirty... (0.25 €/kWh btw). These need a input_number.energy_cost helper, too. EUR/kWh is the Unit for it and the price you have to pay goes in there. This one can be used for the Energy Dash, too and this way the cost are always on one spot.

configuration.yaml:
```
      ocpp1_cost:
        friendly_name: Daniel Kosten
        unique_id: ocpp1_cost
        unit_of_measurement: "€"
        value_template: "{{ (states.sensor.ocpp1_energy.state | float * states('input_number.energy_cost') | float) | round(2) }}"
        device_class: monetary
      ocpp2_cost:
        friendly_name: Andere Kosten
        unique_id: ocpp2_cost
        unit_of_measurement: "€"
        value_template: "{{ (states.sensor.ocpp2_energy.state | float * states('input_number.energy_cost') | float) | round(2) }}"
        device_class: monetary
```

End result:

![image](https://github.com/lbbrhzn/ocpp/assets/29841368/f9204d7a-4fa6-4e82-b061-188db82bc876)

And yes, the kWh values are hand edited to make a nice show off. Right now I still get 0.0 there as already explained above. But as it seems, it really works as expected in my first test.

Now my questions. 
I hope that my automations filling the CSVs are really all cases where a charge session ends. I hope so, but I am open for a more secure way to detect the end of a charge session. So if anyone has another good idea... tell me. What I hate the most is that the session ends not with charge end, but removal of the cable...

My Python script is a bit messy. Any optimization suggestions there are very welcome, too.

Anything else? Tell me. I want this thing to work fine and safe and thus am happy about any suggestions.
