### ISSUE TITLE
Alfen solar charging boost switch

### ISSUE THREAD

**Issue by Rep-Hueman** [lbbrhzn/ocpp#1288]
**Feature request  switch boost charging Alfen in HA**

<img width="583" alt="alfen solar charging boost" src="https://github.com/user-attachments/assets/214f6b51-9fc3-4c1a-a93e-a469f069dda4">

I don't know if there is already a back office key for it. 
I have the latest firmware version 7.0. 2-4322. 
Charging on the generated power from the solar panels works perfectly. 
I just want to be able to charge quickly every now and then. (Boost Charging)
This is currently only possible via ACE Service installer or the MyEve app, but it would be nice if there was a switch for this in Home Assistant

**Comment by drc38** [comment]
You'd need to create a switch and automation in HA, the use ocpp configure action. Assuming there is a custom configuration key for it.

**Comment by netmikey** [comment]
Hi, I'm also interested in this functionality.

I had a look at the specification document from Alfen `ACE NG9 Backoffice Configuration keys 7.0.0.pdf`. I didn't find anything related to boost but I found these 3 configuration keys:

> ### SC-Mode
> SolarCharging optimizes locally generated, excess power as measured by the smart meter. Must have Active Loadbalancing configured.
> - Green: SC-GreenShare is configurable
> - Comfort: SC-ComfortLevel is configurable
> Possible values: Off / Green / Comfort
>
> ### SC-GreenShare
> Only used if "SC-Mode" is configured as 'Green', value in percentages.
> - If set to 0%, charging at minimum power is always possible.
> - If set to 100%, charging will only take place if minimum power to charge is measured as excess power on smart meter
> Charging speed will increase to match excess power as measured on smart meter.
> Values between: 0 - 100
>
> ### SC-ComfortLevel
> Only used if “SC‐Mode” is configured as 'Comfort'. Charging will always start irrespective of amount of excess power as measured on smart meter. Value, in kW, is configured as desired minimum charging power.
> Charging speed will increase above Comfort Level to match excess power as measured on smart meter, never exceeding configured maximum current. If Comfort Level exceeds maximum available current, charging will not exceed maximum.
> Values between: 1,4 - 22

From reading this, it seems to me that `SC-GreenShare` and `SC-ComfortLevel` could be set to the desired values once and that it might be enough to control `SC-Mode` from HomeAssistant. Setting this to `Off` and resetting it to one of the other modes (maybe using an automation) could give the same functionality as the boost knob in the Alfen apps.

This is just from reading the docs, I'll try this out when I have time. ;-)

**Comment by netmikey** [comment]
@drc38 Are the ocpp actions documented somewhere? Is there a way to add an entity for reading a custom configuration key?

**Comment by drc38** [comment]
The general actions are documented in the ocpp standard. If you select one from the list there is example input data also. The response, if any, for configuring a field is returned in the `timestamp_config_response` sensor attributes.

**Comment by netmikey** [comment]
Putting together an entity based on an attribute of `timestamp_config_response` (which will hold responses for different configure actions) seems to be a bit tedious.

Would you guys consider adding Alfen's custom configuration keys as entities?

**Comment by netmikey** [comment]
Just for reference if someone needs to solve this particular problem:

I managed to work around the lack of support for the Alfen-Specific OCPP keys by adding a template select and an automation. 

The template select represents the SC-Mode and allows changing it while the automation polls the charger for the current SC-Mode value so that if it decides to change the mode from outside HA for whatever reason, the new value ends up in HA eventually. Note that the delay between asking for the value and the value actually appearing in the "special response entity" `sensor.ev_charger_timestamp_config_response` might be up to somewhat around 20 seconds.

My template select looks like this (sorry, created via the UI):

![Screen Shot 2024-11-11 at 21 33 45](https://github.com/user-attachments/assets/bcf50683-5cec-4912-b69c-3ddf02de7a14)

My automation looks like this:

```yaml
alias: Poll Solar Charging Mode from EV Charger
description: >-
  This non-OCPP-standard, custom manufacturer value doesn't get read/polled by
  the OCPP integration so it has to be polled manually.
triggers:
  - trigger: time_pattern
    minutes: /10
conditions: []
actions:
  - action: ocpp.get_configuration
    data:
      ocpp_key: SC-Mode
    alias: >-
      Perform action 'Open Charge Point Protocol (OCPP): Get configuration
      values for charger' for ocpp_key 'SC-Mode'
mode: single
```

I'd still welcome it if this integration made it easier to add custom OCPP keys somehow.
