### ISSUE TITLE
charge_box_serial_number on Schneider Electric EVlink Smart Wallbox is too long

### ISSUE THREAD

**Issue by bardahlm** [lbbrhzn/ocpp#213]
## Version of the custom_component

0.3.21

## Configuration

```yaml
[...]
logger:
  default: info
  logs:
    custom_components.hacs: debug
    queueman: debug
    aiogithubapi: debug
    custom_components.ocpp: debug
    websocket: debug

```

## Describe the bug

The charge_box_serial_number on my Schneider Electric EVlink Smart Wallbox is too long, so the BootNotification message fails validation.

## Debug log

```text

ocpp.exceptions.ValidationError: Payload '{'chargeBoxSerialNumber': 'EVB1A22P2RI3N182341200100350795E5', 'chargePointModel': 'EVlink Smart Wallbox', 'chargePointSerialNumber': '3N18310641B55', 'chargePointVendor': 'Schneider Electric', 'firmwareVersion': '3.4.0.2'} for action 'BootNotification' is not valid: 'EVB1A22P2RI3N182341200100350795E5' is too long
```

## Workaround 1

Modify ocpp/v16/schemas/BootNotification.json
```
        "chargeBoxSerialNumber": {
            "type": "string",
            "maxLength": 64
        },
```

## Workaround 2 and possibly fix:

See also https://github.com/mobilityhouse/ocpp/issues/273

Modify line 905 in custom_components/ocpp/api.py:

```
@on(Action.BootNotification)
```

to 

```
@on(Action.BootNotification, skip_schema_validation=True)
```
