### ISSUE TITLE
Upcoming problems with HA 2022.6.0

### ISSUE THREAD

**Issue by dreimer1986** [lbbrhzn/ocpp#522]
## Version of the custom_component

[v0.4.32-beta](https://github.com/lbbrhzn/ocpp/releases/tag/v0.4.32-beta)

## Configuration

```yaml
                "entry_id": "e3e34b48b1f328e6666c85df3085125d",
                "version": 1,
                "domain": "ocpp",
                "title": "central",
                "data": {
                    "host": "0.0.0.0",
                    "port": 9000,
                    "csid": "central",
                    "cpid": "evbox",
                    "max_current": 16,
                    "meter_interval": 60,
                    "idle_interval": 900,
                    "websocket_close_timeout": 10,
                    "WEBSOCKET_PING_TRIES": 2,
                    "websocket_ping_interval": 20,
                    "websocket_ping_timeout": 20,
                    "skip_schema_validation": false,
                    "monitored_variables": "Energy.Active.Import.Register,Current.Import,Current.Offered,Power.Active.Import,Temperature,Voltage,Frequency"
                },
                "options": {},
                "pref_disable_new_entities": false,
                "pref_disable_polling": false,
                "source": "user",
                "unique_id": null,
                "disabled_by": null
```

## Describe the bug

New HA will change the component API as it seems. See logs below:

## Debug log

```text

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for ocpp using this method at custom_components/ocpp/__init__.py, line 73: dr = await device_registry.async_get_registry(hass)

```
