### ISSUE TITLE
Help with automating maximum current

### ISSUE THREAD

**Issue by javierin** [lbbrhzn/ocpp#534]
This is not a bug report or an issue itself. But I am stuck trying to implement a very simple thing:
I am using another HACS component called variable which allows me to (using an automation) put the amount of available excess energy into a variable.

Just for clarification. In Spain we have a power cap that causes the grid to be cut if you exceed the amount of power you pay for. It is important not to surpass this limit unless you want to see how your whole household goes dark.

With that said, I am trying to push the value from this variable (in amps) to the wallbox max_current OCPP entity, but I have failed with every combination I have tried so far.

```
- id: '1654034559268'
  alias: Set Wallbox Current
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /30
  condition: []
  action:
  - service: input_number.set_value
    data_template:
      entity_id:
      - number.wallboxZZZZZ_maximum_current
      value: 11
  mode: single
```

No matter what I put in the value (My last attempts are using a static number),  I always end up getting the following error in the logs:

```
2022-06-02 08:32:10 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities number.wallboxZZZZZ_maximum_current
2022-06-02 08:32:20 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities number.wallboxZZZZZ_maximum_current
```

Any help will be appreciated.
