### ISSUE TITLE
option to disable HA notifications from Ocpp integration

### ISSUE THREAD

**Issue by oraveczt** [lbbrhzn/ocpp#936]
This is not an operational problem, however it's quite frustrating that my ABB wall charger triggers "Security event notification received: SettingSystemTime" kind of notifications in Home Assistant on a daily basis.

I could not figure out how to mute these.

Can you add some sort of config options to the Ocpp integration to be able to mute these kind of notifications?

**Comment by drc38** [comment]
Simply create an automation eg
```
trigger:
  - platform: persistent_notification
    update_type:
      - added
    notification_id: ""
condition:
  - condition: template
    value_template: "{{ trigger.notification.title | lower == \"ocpp integration\" }}"
action:
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: persistent_notification.dismiss
    data:
      notification_id: trigger.notification.notification_id
mode: single
```
